name: core
description: A new Flutter package.
#version: 0.0.1
#author:
#homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart:
  http:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
